esphome:
  name: wemos_lvv
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_ssid_passwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos Lvv Fallback Hotspot"
    password: "67IBKzeodCIM"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# virranmittaus
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "Measured Current"
    update_interval: 60s
  - platform: dallas
    address: 0x27051686AF9CFF28
    name: "lvp1"  

  # Example source sensor
  - platform: adc
    pin: A0
    id: adc_sensor
    
dallas:
  - pin: D2
  

  